"""System control: start/stop/status/mode/settings."""
import json
import logging
import subprocess
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.database import get_session
from app.models import BalancerGroup, Device, DNSRule, Node, RoutingRule, RoutingSet, Settings as DBSettings
from app.core.device_scanner import get_device_macs_for_mode
from app.schemas import (
    ActiveNodeUpdate,
    DataVersions,
    HostVersions,
    ModeUpdate,
    PitunVersions,
    RuntimeVersions,
    SettingsRead,
    SettingsUpdate,
    SystemStatus,
    SystemVersions,
    ThirdPartyVersions,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/system", tags=["system"])


def _safe_int(settings_map: dict, key: str, default: int) -> int:
    """Read an integer setting with a hardened fallback.

    DB Settings are stored as strings and can be corrupted (manual edit,
    bad migration, UI glitch) — a single bad value previously crashed
    `/start` with a bare `ValueError` from `int("abc")` and left the user
    unable to bring up the proxy. This helper returns `default` on any
    parse failure instead.
    """
    try:
        raw = settings_map.get(key)
        if raw is None or raw == "":
            return default
        return int(raw)
    except (TypeError, ValueError):
        import logging
        logging.getLogger(__name__).warning(
            "Invalid int value for setting %r: %r — falling back to %d",
            key, settings_map.get(key), default,
        )
        return default


def _detect_ip(interface: str) -> str:
    """Auto-detect the first IPv4 address on `interface` via `ip -j addr`."""
    try:
        out = subprocess.run(
            ["ip", "-j", "-4", "addr", "show", interface],
            capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0 and out.stdout.strip():
            import json as _json
            data = _json.loads(out.stdout)
            for iface in data:
                for info in iface.get("addr_info", []):
                    addr = info.get("local", "")
                    if addr:
                        return addr
    except Exception:
        pass
    return ""


def _detect_cidr(interface: str) -> str:
    """Auto-detect the LAN subnet (network/prefix) on `interface`.

    Mirrors `_detect_ip` but returns a CIDR like ``192.168.88.0/24`` —
    derived from the host's IP and the interface prefix length. Used as
    a runtime fallback for ``lan_cidr`` when the .env was generated by
    an older installer that left the example default in place.
    """
    try:
        out = subprocess.run(
            ["ip", "-j", "-4", "addr", "show", interface],
            capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0 and out.stdout.strip():
            import json as _json
            import ipaddress as _ipaddress

            data = _json.loads(out.stdout)
            for iface in data:
                for info in iface.get("addr_info", []):
                    addr = info.get("local", "")
                    prefix = info.get("prefixlen")
                    if addr and prefix is not None:
                        try:
                            net = _ipaddress.ip_network(f"{addr}/{prefix}", strict=False)
                            return str(net)
                        except ValueError:
                            continue
    except Exception:
        pass
    return ""


_HOST_PROC_SYS = "/host/proc_sys"   # bind-mounted from host /proc/sys
_HOST_RESOLV = "/host/resolv.conf"  # bind-mounted from host /etc/resolv.conf


async def apply_system_toggles_on_boot() -> None:
    """Apply disable_ipv6 and dns_over_tcp from DB to host on startup.

    /proc/sys values reset after reboot, so we re-apply saved state.
    resolv.conf survives reboot, but we ensure consistency anyway.
    """
    import logging
    _log = logging.getLogger(__name__)

    try:
        from sqlmodel import select
        from sqlmodel.ext.asyncio.session import AsyncSession
        from app.database import get_async_engine
        from app.models import Settings as DBSettings

        async with AsyncSession(get_async_engine()) as session:
            rows = (await session.exec(select(DBSettings))).all()
            m = {r.key: r.value for r in rows}

        # IPv6
        disable_ipv6 = m.get("disable_ipv6", "false").lower() == "true"
        val = "1" if disable_ipv6 else "0"
        for path in ("net/ipv6/conf/all/disable_ipv6", "net/ipv6/conf/default/disable_ipv6"):
            try:
                with open(f"{_HOST_PROC_SYS}/{path}", "w") as f:
                    f.write(val)
            except Exception:
                pass
        _log.info("Applied disable_ipv6=%s on boot", disable_ipv6)

        # DNS over TCP
        dns_over_tcp = m.get("dns_over_tcp", "false").lower() == "true"
        try:
            with open(_HOST_RESOLV) as f:
                lines = [l for l in f.read().splitlines() if "use-vc" not in l]
            if dns_over_tcp:
                lines.append("options use-vc")
            with open(_HOST_RESOLV, "w") as f:
                f.write("\n".join(lines) + "\n")
            _log.info("Applied dns_over_tcp=%s on boot", dns_over_tcp)
        except Exception:
            pass

        # Host fallback DNS — additive resolvers for the box's own
        # resolution. Idempotent, so re-applying on every boot is safe
        # and self-heals if NetworkManager/DHCP dropped our entries.
        host_fallback = m.get("host_fallback_dns", "").strip()
        if host_fallback:
            try:
                from app.core.network_apply import apply_host_fallback_dns
                servers = [s.strip() for s in host_fallback.split(",") if s.strip()]
                res = apply_host_fallback_dns(servers)
                _log.info("Applied host_fallback_dns on boot: %s", res.get("detail"))
            except Exception as exc:
                _log.warning("host_fallback_dns boot apply failed: %s", exc)

    except Exception as exc:
        _log.warning("Failed to apply system toggles on boot: %s", exc)


def _detect_sysctl_bool(key: str, fallback: bool) -> bool:
    """Read a sysctl value from host /proc/sys (bind-mounted)."""
    try:
        proc_path = _HOST_PROC_SYS + "/" + key.replace(".", "/")
        with open(proc_path) as f:
            return f.read().strip() == "1"
    except Exception:
        return fallback


def _detect_resolv_use_vc(fallback: bool) -> bool:
    """Check if host /etc/resolv.conf contains 'options use-vc'."""
    try:
        with open(_HOST_RESOLV) as f:
            return "use-vc" in f.read()
    except Exception:
        return fallback


# ── Helper ────────────────────────────────────────────────────────────────────

async def _get_setting(session: AsyncSession, key: str) -> Optional[str]:
    row = (await session.exec(select(DBSettings).where(DBSettings.key == key))).first()
    return row.value if row else None


async def _set_setting(session: AsyncSession, key: str, value: str) -> None:
    row = (await session.exec(select(DBSettings).where(DBSettings.key == key))).first()
    if row:
        row.value = value
        session.add(row)
    else:
        session.add(DBSettings(key=key, value=value))


async def _collect_vpn_server_ips(session: AsyncSession) -> List[str]:
    nodes = (await session.exec(select(Node).where(Node.enabled == True))).all()
    return list({n.address for n in nodes if n.address})


# ── Status ────────────────────────────────────────────────────────────────────

@router.get("/status", response_model=SystemStatus)
async def get_status(session: AsyncSession = Depends(get_session)):
    from app.core.xray import xray_manager
    from app.core.nftables import nftables_manager

    mode = await _get_setting(session, "mode") or "rules"
    active_id_str = await _get_setting(session, "active_node_id") or ""
    active_node = None
    active_node_id = None
    if active_id_str:
        try:
            active_node_id = int(active_id_str)
            active_node = await session.get(Node, active_node_id)
        except ValueError:
            pass

    version = xray_manager.version or await xray_manager.get_version()
    nft_active = await nftables_manager.is_active()

    # Last xray config validation error (written by config_gen.write_config
    # since v1.2.5). None / empty means the most recent validation passed
    # — frontend hides the banner.
    last_validation_error = await _get_setting(session, "last_xray_validation_error")

    from app.config import APP_VERSION
    return SystemStatus(
        running=xray_manager.is_running,
        pid=xray_manager.pid,
        uptime_seconds=xray_manager.uptime,
        mode=mode,
        active_node_id=active_node_id,
        active_node_name=active_node.name if active_node else None,
        nftables_active=nft_active,
        version=version,
        app_version=APP_VERSION,
        last_xray_validation_error=last_validation_error or None,
    )


# ── Full version snapshot ─────────────────────────────────────────────────────

@router.get("/versions", response_model=SystemVersions)
async def get_versions():
    """Gather a complete version dump for the sidebar popover / About tab.

    Each sub-section is defensive: a missing /etc/os-release or broken
    docker socket degrades to `None`, the rest of the response still
    renders. PiTun-owned versions come from `app.config.APP_VERSION`
    (single source of truth — bump once, read everywhere).
    """
    import logging
    import os
    from datetime import datetime, timezone
    import platform

    from app.config import APP_VERSION, settings
    from app.core.xray import xray_manager

    log = logging.getLogger(__name__)

    pitun = PitunVersions(backend=APP_VERSION, naive_image=APP_VERSION)

    # Runtime: xray binary, python interpreter.
    xray_ver = xray_manager.version or await xray_manager.get_version()
    runtime = RuntimeVersions(xray=xray_ver, python=platform.python_version())

    # Host: `pid: host` in compose means `os.uname()` already returns the
    # host kernel — no bind-mount needed for that. For the distro name we
    # look at `/host/os-release` (bind-mounted in compose); fall back to
    # `/etc/os-release` which — inside the backend image — is Debian
    # (python:3.11-slim), NOT the real host, so we flag it as such to
    # avoid confusing the user.
    host = HostVersions()
    try:
        uname = os.uname()
        host.kernel = uname.release
        host.arch = uname.machine
    except Exception as exc:
        log.debug("versions: uname failed: %s", exc)

    host_release_candidates = ["/host/os-release", "/host/etc/os-release"]
    os_release_src = next((p for p in host_release_candidates if os.path.exists(p)), None)
    if os_release_src:
        try:
            host.os = _parse_os_release(os_release_src)
        except Exception as exc:
            log.debug("versions: parsing %s failed: %s", os_release_src, exc)
    else:
        # Fall back to container's own /etc/os-release, but mark it so the
        # UI knows this is NOT the host distro. Better than showing nothing.
        try:
            distro = _parse_os_release("/etc/os-release")
            host.os = f"{distro} (container)" if distro else None
        except Exception as exc:
            log.debug("versions: /etc/os-release parse failed: %s", exc)

    # Docker engine version + the nginx container image tag (the nginx
    # running as reverse proxy is `pitun-nginx`). We skip `pitun-frontend`
    # entirely — it IS built on nginx:alpine but the user-facing "nginx
    # version" should reflect the actual ingress proxy. `pitun-docker-proxy`
    # only exists with COMPOSE_PROFILES=secure.
    third_party = ThirdPartyVersions()
    try:
        from app.core.naive_manager import naive_manager
        client = naive_manager._get_client()
        host.docker = client.version().get("Version")
        for ctr_name, attr in (("pitun-nginx", "nginx"), ("pitun-docker-proxy", "socket_proxy")):
            try:
                c = client.containers.get(ctr_name)
                tag = c.image.tags[0] if c.image.tags else c.image.id[:12]
                setattr(third_party, attr, _short_tag(tag))
            except Exception:
                continue
    except Exception as exc:
        log.debug("versions: docker client introspection failed: %s", exc)

    # Data: migration HEAD from alembic_version table + geo-data mtimes
    # so the user can tell how stale the xray rules are without opening
    # the GeoData page.
    data_block = DataVersions()
    try:
        from sqlmodel.ext.asyncio.session import AsyncSession
        from sqlalchemy import text as sql_text
        from app.database import get_async_engine
        async with AsyncSession(get_async_engine()) as session:
            result = await session.execute(sql_text("SELECT version_num FROM alembic_version"))
            row = result.first()
            if row:
                data_block.alembic_rev = row[0]
    except Exception as exc:
        log.debug("versions: alembic_version query failed: %s", exc)

    for attr, path in (
        ("geoip_mtime", settings.xray_geoip_path),
        ("geosite_mtime", settings.xray_geosite_path),
    ):
        try:
            if os.path.exists(path):
                ts = os.stat(path).st_mtime
                iso = datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()
                setattr(data_block, attr, iso)
        except Exception as exc:
            log.debug("versions: stat %s failed: %s", path, exc)

    return SystemVersions(
        pitun=pitun,
        runtime=runtime,
        third_party=third_party,
        host=host,
        data=data_block,
    )


def _parse_os_release(path: str) -> str | None:
    """Extract PRETTY_NAME from /etc/os-release-style files."""
    with open(path, "r") as f:
        entries = dict(
            line.strip().split("=", 1)
            for line in f
            if "=" in line and not line.startswith("#")
        )
    return entries.get("PRETTY_NAME", "").strip('"') or None


def _short_tag(tag: str) -> str:
    """Strip registry prefix from a docker image tag for display."""
    if ":" in tag:
        return tag.rsplit("/", 1)[-1]
    return tag


# ── Start / Stop / Restart ────────────────────────────────────────────────────

async def _apply_nftables(session: AsyncSession, settings_map: dict) -> str:
    """Apply nftables rules with device filtering. Returns inbound_mode."""
    from app.core.nftables import nftables_manager, RoutingSetSpec
    from app.core.config_gen import collect_routing_set_context

    mode = settings_map.get("mode", "rules")
    inbound_mode = settings_map.get("inbound_mode", "tproxy")

    # Bypass mode: no tproxy needed — flush nftables and let traffic go direct
    if mode == "bypass":
        await nftables_manager.flush()
        return inbound_mode

    rules = list((await session.exec(select(RoutingRule).where(RoutingRule.enabled == True))).all())
    bypass_macs = _collect_bypass_macs(rules)
    bypass_dsts = _collect_bypass_dsts(rules)

    # Auto-bypass all enabled naive upstream server IPs. The sidecar runs in
    # host netns and opens a plain TCP socket to its upstream — without this
    # the output mangle hook would mark that packet for tproxy and loop it
    # back through xray → the naive sidecar → forever. Xray's own outbounds
    # set SO_MARK=255 to break the loop; naive can't, so we bypass by dest.
    naive_dsts = await _collect_naive_bypass_dsts(session)
    if naive_dsts:
        bypass_dsts = list(bypass_dsts) + naive_dsts

    device_info = await get_device_macs_for_mode(session)
    device_mode = device_info["mode"]

    if device_mode == "exclude_list":
        bypass_macs.extend(device_info["exclude_macs"])

    # Per-RoutingSet nftables plumbing (v1.4). Build one RoutingSetSpec
    # per non-empty set so nftables can render its MAC set + per-set
    # TPROXY redirect. Empty sets are skipped — they generate no
    # plumbing and config_gen also omits their xray inbound, so the
    # rendering stays in sync between the two layers.
    routing_sets, device_set_macs = await collect_routing_set_context(session)
    routing_set_specs: list[RoutingSetSpec] = []
    for rs in routing_sets:
        macs = device_set_macs.get(rs.id) or []
        if not macs:
            continue
        routing_set_specs.append(RoutingSetSpec(
            set_id=rs.id,
            macs=tuple(macs),
            tproxy_port=rs.tproxy_port,
        ))

    await nftables_manager.apply_rules(
        inbound_mode=inbound_mode,
        bypass_macs=bypass_macs,
        bypass_dst_cidrs=bypass_dsts,
        include_macs=device_info["include_macs"] if device_mode == "include_only" else None,
        device_routing_mode=device_mode,
        tproxy_tcp=_safe_int(settings_map, "tproxy_port_tcp", 7893),
        tproxy_udp=_safe_int(settings_map, "tproxy_port_udp", 7894),
        dns_port=_safe_int(settings_map, "dns_port", 5353),
        block_quic=settings_map.get("block_quic", "true").lower() == "true",
        kill_switch=settings_map.get("kill_switch", "false").lower() == "true",
        routing_set_specs=routing_set_specs,
        proxy_local_apps=settings_map.get("proxy_local_apps", "false").lower() == "true",
    )
    return inbound_mode


@router.post("/start", status_code=204)
async def start_proxy(session: AsyncSession = Depends(get_session)):
    from app.core.xray import xray_manager

    await _regenerate_and_write(session)
    settings_map = await _load_settings_map(session)
    inbound_mode = await _apply_nftables(session, settings_map)

    if xray_manager.is_running:
        await xray_manager.reload()
    else:
        await xray_manager.start()

    if inbound_mode in ("tun", "both"):
        auto_route = settings_map.get("tun_auto_route", "true").lower() == "true"
        if not auto_route:
            from app.core.tun import setup_tun
            import app.core.xray as xray_mod
            await setup_tun(
                address=settings_map.get("tun_address", "10.0.0.1/30"),
                mtu=_safe_int(settings_map, "tun_mtu", 9000),
            )
            xray_mod._tun_active = True
        else:
            import app.core.xray as xray_mod
            xray_mod._tun_active = True


@router.post("/stop", status_code=204)
async def stop_proxy(session: AsyncSession = Depends(get_session)):
    from app.core.xray import xray_manager
    from app.core.nftables import nftables_manager

    settings_map = await _load_settings_map(session)
    kill_switch = settings_map.get("kill_switch", "false").lower() == "true"
    if kill_switch:
        vpn_ips = await _collect_vpn_server_ips(session)
        await nftables_manager.apply_kill_switch(vpn_server_ips=vpn_ips)

    await xray_manager.stop()

    if not kill_switch:
        await nftables_manager.flush()


@router.post("/restart", status_code=204)
async def restart_proxy(session: AsyncSession = Depends(get_session)):
    from app.core.xray import xray_manager

    await _regenerate_and_write(session)
    settings_map = await _load_settings_map(session)
    inbound_mode = await _apply_nftables(session, settings_map)

    await xray_manager.restart()

    if inbound_mode in ("tun", "both"):
        auto_route = settings_map.get("tun_auto_route", "true").lower() == "true"
        if not auto_route:
            from app.core.tun import setup_tun
            await setup_tun(
                address=settings_map.get("tun_address", "10.0.0.1/30"),
                mtu=_safe_int(settings_map, "tun_mtu", 9000),
            )
        import app.core.xray as xray_mod
        xray_mod._tun_active = True


@router.post("/reload-config", status_code=204)
async def reload_config(session: AsyncSession = Depends(get_session)):
    """Regenerate xray config, re-apply nftables, and hot-reload."""
    from app.core.xray import xray_manager

    await _regenerate_and_write(session)
    settings_map = await _load_settings_map(session)
    await _apply_nftables(session, settings_map)

    if xray_manager.is_running:
        await xray_manager.reload()


# ── Mode ──────────────────────────────────────────────────────────────────────

@router.post("/mode", status_code=204)
async def set_mode(body: ModeUpdate, session: AsyncSession = Depends(get_session)):
    await _set_setting(session, "mode", body.mode)
    await session.commit()


async def _pin_circle_balancer(session: AsyncSession, node_id: int) -> None:
    """If `node_id` belongs to a running NodeCircle, pin that circle's xray
    balancer to it via gRPC balancerOverride. The config routes circle proxy
    traffic at a balancer over all members (cold-start strategy = random), so
    after a (re)load we must override to the actually-selected node.
    Best-effort — silently skipped if the API isn't up."""
    try:
        from app.core import xray_api
        from app.core.config_gen import resolve_active_circle
        from app.models import NodeCircle
        circles = list((await session.exec(select(NodeCircle))).all())
        cid, member_ids = resolve_active_circle(circles, node_id)
        if cid and node_id in (member_ids or []) and await xray_api.is_api_available():
            await xray_api.override_balancer(f"circle-{cid}", [f"node-{node_id}"])
    except Exception as exc:
        logging.getLogger(__name__).debug("pin circle balancer skipped: %s", exc)


@router.post("/active-node", status_code=204)
async def set_active_node(body: ActiveNodeUpdate, session: AsyncSession = Depends(get_session)):
    from app.core.xray import xray_manager

    node = await session.get(Node, body.node_id)
    if not node:
        raise HTTPException(404, "Node not found")
    await _set_setting(session, "active_node_id", str(body.node_id))
    await session.commit()

    # Switching the active node must actually APPLY it: regenerate the xray
    # config (picks the new active outbound + wires its chain) and hot-reload.
    # Without this the DB flips but xray keeps serving the PREVIOUS node — so
    # activating a WireGuard chain left traffic exiting the old node and the
    # real exit IP never changed, even though the UI showed the new node.
    await _regenerate_and_write(session)
    settings_map = await _load_settings_map(session)
    await _apply_nftables(session, settings_map)
    if xray_manager.is_running:
        await xray_manager.reload()
    await _pin_circle_balancer(session, body.node_id)


# ── Settings ──────────────────────────────────────────────────────────────────

@router.get("/settings", response_model=SettingsRead)
async def get_settings(session: AsyncSession = Depends(get_session)):
    m = await _load_settings_map(session)
    active_id: Optional[int] = None
    if m.get("active_node_id"):
        try:
            active_id = int(m["active_node_id"])
        except ValueError:
            pass

    failover_ids: List[int] = []
    if m.get("failover_node_ids"):
        try:
            failover_ids = json.loads(m["failover_node_ids"])
        except (ValueError, json.JSONDecodeError):
            pass

    from app.config import settings as env_settings

    def _int(key: str, default: int) -> int:
        try:
            return int(m.get(key, str(default)))
        except (ValueError, TypeError):
            return default

    # Auto-detect PiTun IP from interface; sync to DB so device_scanner sees it
    iface = m.get("interface") or env_settings.interface
    detected_ip = _detect_ip(iface)
    effective_ip = detected_ip or m.get("gateway_ip") or env_settings.gateway_ip
    if detected_ip and m.get("gateway_ip") != detected_ip:
        row = await session.exec(select(DBSettings).where(DBSettings.key == "gateway_ip"))
        s = row.first()
        if s:
            s.value = detected_ip
        else:
            session.add(DBSettings(key="gateway_ip", value=detected_ip))
        await session.commit()

    # LAN CIDR fallback: prefer DB value (user override or set by an
    # up-to-date installer), then the live interface prefix, then the
    # .env default. We do NOT write the detected CIDR back to DB here —
    # that would silently overwrite a deliberate manual value if the
    # interface ever flips to a different subnet.
    db_cidr = m.get("lan_cidr")
    detected_cidr = _detect_cidr(iface) if not db_cidr else ""
    effective_cidr = db_cidr or detected_cidr or env_settings.lan_cidr

    return SettingsRead(
        mode=m.get("mode", "rules"),
        active_node_id=active_id,
        failover_enabled=m.get("failover_enabled", "false").lower() == "true",
        failover_node_ids=failover_ids,
        # Network — auto-detected gateway_ip synced to DB
        interface=iface,
        gateway_ip=effective_ip,
        lan_cidr=effective_cidr,
        router_ip=m.get("router_ip", ""),
        # Ports
        tproxy_port_tcp=_int("tproxy_port_tcp", 7893),
        tproxy_port_udp=_int("tproxy_port_udp", 7894),
        socks_port=_int("socks_port", 1080),
        http_port=_int("http_port", 8080),
        dns_port=_int("dns_port", 5353),
        dns_mode=m.get("dns_mode", "plain"),
        dns_upstream=m.get("dns_upstream", "8.8.8.8"),
        dns_upstream_secondary=m.get("dns_upstream_secondary") or None,
        dns_fallback=m.get("dns_fallback") or None,
        fakedns_enabled=m.get("fakedns_enabled", "false").lower() == "true",
        fakedns_pool=m.get("fakedns_pool", "198.18.0.0/15"),
        fakedns_pool_size=_int("fakedns_pool_size", 65535),
        dns_sniffing=m.get("dns_sniffing", "true").lower() == "true",
        bypass_cn_dns=m.get("bypass_cn_dns", "false").lower() == "true",
        bypass_ru_dns=m.get("bypass_ru_dns", "false").lower() == "true",
        bypass_private=m.get("bypass_private", "true").lower() == "true",
        log_level=m.get("log_level", "warning"),
        geoip_url=m.get("geoip_url", ""),
        geosite_url=m.get("geosite_url", ""),
        geoip_mmdb_url=m.get("geoip_mmdb_url") or None,
        # v1.4.7 — finding 3.1. Persisted in init_default_settings.
        dns_route_via=m.get("dns_route_via", "direct") or "direct",
        # v1.4.7 — finding 3.5. Default False = box-local traffic bypasses xray.
        proxy_local_apps=m.get("proxy_local_apps", "false").lower() == "true",
        inbound_mode=m.get("inbound_mode", "tproxy"),
        tun_address=m.get("tun_address", "10.0.0.1/30"),
        tun_mtu=_int("tun_mtu", 9000),
        tun_stack=m.get("tun_stack", "system"),
        tun_auto_route=m.get("tun_auto_route", "true").lower() == "true",
        tun_strict_route=m.get("tun_strict_route", "true").lower() == "true",
        block_quic=m.get("block_quic", "true").lower() == "true",
        kill_switch=m.get("kill_switch", "false").lower() == "true",
        auto_restart_xray=m.get("auto_restart_xray", "true").lower() == "true",
        dns_query_log_enabled=m.get("dns_query_log_enabled", "false").lower() == "true",
        device_routing_mode=m.get("device_routing_mode", "all"),
        disable_ipv6=_detect_sysctl_bool("net.ipv6.conf.all.disable_ipv6", m.get("disable_ipv6", "false").lower() == "true"),
        dns_over_tcp=_detect_resolv_use_vc(m.get("dns_over_tcp", "false").lower() == "true"),
        health_interval=_int("health_interval", env_settings.health_interval),
        health_timeout=_int("health_timeout", env_settings.health_timeout),
        health_full_check_interval=_int("health_full_check_interval", 300),
        # GeoScheduler knobs — read from DB (init_default_settings seeds them).
        # Pydantic defaults would mask whatever the user actually picked,
        # so the fall-through value matches the seed defaults.
        geo_auto_update=m.get("geo_auto_update", "true").lower() == "true",
        geo_update_interval_days=_int("geo_update_interval_days", 1),
        geo_update_window_start=_int("geo_update_window_start", 4),
        geo_update_window_end=_int("geo_update_window_end", 6),
        timezone=m.get("timezone", "UTC"),
        # LAN proxy auth (since v1.3.0-beta.6) — single (user, pass)
        # pair shared by the SOCKS5 and HTTP inbounds. Plaintext on
        # the wire by design (LAN-intruder threat model).
        lan_proxy_auth_enabled=m.get("lan_proxy_auth_enabled", "false").lower() == "true",
        lan_proxy_auth_user=m.get("lan_proxy_auth_user", ""),
        lan_proxy_auth_pass=m.get("lan_proxy_auth_pass", ""),
    )


@router.get("/stats")
async def get_traffic_stats():
    from app.core.stats import get_outbound_stats
    return await get_outbound_stats()


_metrics_cache: dict = {"period": "", "ts": 0.0, "data": []}
_METRICS_CACHE_TTL = 30.0  # seconds


@router.get("/metrics")
async def get_system_metrics(
    period: str = "1h",
    session: AsyncSession = Depends(get_session),
):
    """System metrics for dashboard charts.

    period: 15m, 1h, 3h, 6h, 12h, 1d, 3d
    """
    import time
    from datetime import datetime, timedelta, timezone
    from app.models import SystemMetric

    # Simple in-memory cache — avoids repeated DB queries from multiple clients
    now = time.monotonic()
    if _metrics_cache["period"] == period and (now - _metrics_cache["ts"]) < _METRICS_CACHE_TTL:
        return _metrics_cache["data"]

    multipliers = {
        "15m": timedelta(minutes=15),
        "1h": timedelta(hours=1),
        "3h": timedelta(hours=3),
        "6h": timedelta(hours=6),
        "12h": timedelta(hours=12),
        "1d": timedelta(days=1),
        "3d": timedelta(days=3),
    }
    delta = multipliers.get(period, timedelta(hours=1))
    since = datetime.now(timezone.utc) - delta

    rows = (await session.exec(
        select(SystemMetric)
        .where(SystemMetric.ts >= since)
        .order_by(SystemMetric.ts)
    )).all()

    # Downsample to at most ~300 points — SVG charts choke on thousands of
    # path points (Firefox STATUS_BREAKPOINT on re-render).
    _MAX_POINTS = 300
    if len(rows) > _MAX_POINTS:
        step = len(rows) // _MAX_POINTS + 1
        rows = rows[::step]

    result = [
        {
            "ts": r.ts.strftime("%Y-%m-%dT%H:%M:%SZ") if r.ts else None,
            "cpu": r.cpu_percent,
            "ram_used": r.ram_used_mb,
            "ram_total": r.ram_total_mb,
            "disk_used": r.disk_used_gb,
            "disk_total": r.disk_total_gb,
            "net_sent": r.net_sent_bytes,
            "net_recv": r.net_recv_bytes,
        }
        for r in rows
    ]

    _metrics_cache["period"] = period
    _metrics_cache["ts"] = now
    _metrics_cache["data"] = result
    return result


@router.patch("/settings", status_code=204)
async def update_settings(body: SettingsUpdate, session: AsyncSession = Depends(get_session)):
    patches = body.model_dump(exclude_unset=True)

    # LAN proxy auth invariant — when the user enables auth, both
    # username and password must be non-empty. Validate against the
    # *post-merge* state: if the patch flips `_enabled=true` but
    # doesn't ship creds, fall back to the existing DB values; if
    # those are also empty, reject with 400 (rather than letting
    # config_gen blow up on the next start_proxy call with a
    # confusing ValueError).
    if patches.get("lan_proxy_auth_enabled") is True:
        existing = {r.key: r.value for r in (await session.exec(select(DBSettings))).all()}
        new_user = (
            patches.get("lan_proxy_auth_user")
            if patches.get("lan_proxy_auth_user") is not None
            else existing.get("lan_proxy_auth_user", "")
        )
        new_pass = (
            patches.get("lan_proxy_auth_pass")
            if patches.get("lan_proxy_auth_pass") is not None
            else existing.get("lan_proxy_auth_pass", "")
        )
        if not (new_user or "").strip() or not new_pass:
            raise HTTPException(
                status_code=400,
                detail=(
                    "LAN proxy auth requires both `lan_proxy_auth_user` "
                    "and `lan_proxy_auth_pass` to be non-empty when "
                    "`lan_proxy_auth_enabled=true`."
                ),
            )

    # Snapshot `inbound_mode` BEFORE the patch so we can roll back if
    # the new value generates an invalid xray config. Without this, the
    # PATCH would persist e.g. `inbound_mode=tun` even though xray
    # rejects the resulting config — the UI then shows "TUN" selected
    # but the runtime keeps the old mode. See backlog item 1 in
    # notes.md ("TUN/Both silently bricks proxy"). The snapshot is
    # cheap: a single Settings row read.
    inbound_mode_was = None
    if "inbound_mode" in patches and patches["inbound_mode"] is not None:
        existing_row = (await session.exec(
            select(DBSettings).where(DBSettings.key == "inbound_mode")
        )).first()
        inbound_mode_was = existing_row.value if existing_row else "tproxy"

    for key, value in patches.items():
        if value is None:
            continue
        if key == "failover_node_ids":
            await _set_setting(session, key, json.dumps(value))
        elif isinstance(value, bool):
            await _set_setting(session, key, str(value).lower())
        elif isinstance(value, int):
            await _set_setting(session, key, str(value))
        else:
            await _set_setting(session, key, str(value))
    await session.commit()

    # Post-commit pre-flight for inbound_mode changes. We commit first
    # (so the helper that loads settings_map sees the new value), then
    # generate + validate. On failure, rewrite the row back to its old
    # value and raise 400 — the UI's mutation will surface the error
    # and stay on the previous mode. xray-side state is untouched
    # because we never restarted it (writing config.json is harmless
    # if xray isn't reloaded).
    if (
        inbound_mode_was is not None
        and str(patches.get("inbound_mode")) != inbound_mode_was
    ):
        from app.core.config_gen import (
            generate_config, write_config,
            _diagnose_empty_stderr, _xray_version,
        )
        from pathlib import Path
        from app.config import settings as app_settings
        import asyncio

        # Generate a candidate config under the new mode. We can't
        # simply call _regenerate_and_write because that path triggers
        # self-healing of geo rules — orthogonal to mode validation
        # and would mask the real "this mode is unsupported" error.
        settings_map = await _load_settings_map(session)
        active_id_str = settings_map.get("active_node_id", "")
        active_node = None
        if active_id_str:
            try:
                active_node = await session.get(Node, int(active_id_str))
            except ValueError:
                pass
        all_nodes = list((await session.exec(select(Node).where(Node.enabled == True))).all())
        rules = list((await session.exec(select(RoutingRule).where(RoutingRule.enabled == True))).all())
        dns_rules = list((await session.exec(select(DNSRule).where(DNSRule.enabled == True))).all())
        balancer_groups = list((await session.exec(select(BalancerGroup))).all())
        from app.core.config_gen import collect_routing_set_context
        routing_sets, device_set_macs = await collect_routing_set_context(session)
        candidate = generate_config(
            active_node, all_nodes, rules,
            settings_map.get("mode", "rules"),
            settings_map, dns_rules, balancer_groups,
            routing_sets=routing_sets, device_set_macs=device_set_macs,
        )

        # In-process pre-flight: write to a tmp path and run xray -test
        # there. NOT the real config.json — we don't want a successful
        # write that gets overridden on rollback.
        ok = True
        diag = "unknown error"
        try:
            if Path(app_settings.xray_binary).exists():
                tmp_path = f"{app_settings.xray_config_path}.candidate"
                import json as _json
                Path(tmp_path).parent.mkdir(parents=True, exist_ok=True)
                with open(tmp_path, "w") as f:
                    _json.dump(candidate, f, indent=2)
                proc = await asyncio.create_subprocess_exec(
                    app_settings.xray_binary, "run", "-test", "-config", tmp_path,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                _, stderr = await asyncio.wait_for(proc.communicate(), timeout=10)
                Path(tmp_path).unlink(missing_ok=True)
                if proc.returncode != 0:
                    ok = False
                    stderr_text = stderr.decode(errors="replace").strip()
                    if not stderr_text:
                        ver = await _xray_version()
                        diag = _diagnose_empty_stderr(
                            xray_version=ver,
                            inbound_mode=patches.get("inbound_mode"),
                            config=candidate,
                        )
                    else:
                        diag = stderr_text.splitlines()[-1][:300]
        except Exception as exc:  # noqa: BLE001
            # Pre-flight failure due to binary missing / hung etc is
            # advisory only — let the value through. Same policy as
            # `write_config` (advisory pre-flight).
            import logging
            logging.getLogger(__name__).debug(
                "inbound_mode pre-flight skipped: %s", exc,
            )

        if not ok:
            # Roll back the inbound_mode row + commit so DB reflects
            # reality. Other patched keys stay applied (they didn't
            # cause the failure).
            await _set_setting(session, "inbound_mode", inbound_mode_was)
            await session.commit()
            raise HTTPException(
                status_code=400,
                detail=(
                    f"Inbound mode '{patches['inbound_mode']}' produces an "
                    f"invalid xray config — change reverted. "
                    f"Details: {diag}"
                ),
            )

    # Apply IPv6 toggle via bind-mounted host /proc/sys
    if "disable_ipv6" in patches:
        val = "1" if patches["disable_ipv6"] else "0"
        for path in ("net/ipv6/conf/all/disable_ipv6", "net/ipv6/conf/default/disable_ipv6"):
            try:
                with open(f"{_HOST_PROC_SYS}/{path}", "w") as f:
                    f.write(val)
            except Exception:
                pass

    # Apply DNS over TCP toggle via bind-mounted host /etc/resolv.conf
    if "dns_over_tcp" in patches:
        try:
            with open(_HOST_RESOLV) as f:
                lines = [l for l in f.read().splitlines() if "use-vc" not in l]
            if patches["dns_over_tcp"]:
                lines.append("options use-vc")
            with open(_HOST_RESOLV, "w") as f:
                f.write("\n".join(lines) + "\n")
        except Exception:
            pass

    # Apply host fallback DNS additively (NM / systemd-resolved /
    # resolv.conf depending on what the host runs). Non-destructive —
    # keeps the DHCP/router DNS primary, appends our fallbacks.
    if "host_fallback_dns" in patches:
        try:
            from app.core.network_apply import apply_host_fallback_dns
            raw = str(patches["host_fallback_dns"] or "")
            servers = [s.strip() for s in raw.split(",") if s.strip()]
            apply_host_fallback_dns(servers)
        except Exception as exc:
            logger.warning("host_fallback_dns apply failed: %s", exc)

    # LAN proxy auth changes affect the running xray config (SOCKS +
    # HTTP inbounds get `accounts` injected/removed). Reload xray on
    # the fly so the user sees the change without going to /restart —
    # they toggle this from the Dashboard inline UI and expect
    # immediate effect. Skipped silently if xray isn't running.
    lan_auth_keys = {
        "lan_proxy_auth_enabled",
        "lan_proxy_auth_user",
        "lan_proxy_auth_pass",
    }
    if patches.keys() & lan_auth_keys:
        try:
            from app.core.xray import xray_manager
            if xray_manager.is_running:
                await _regenerate_and_write(session)
                await xray_manager.reload()
        except Exception as exc:
            # Log and continue — the next manual /start will pick up
            # the new creds anyway. Don't 500 the PATCH because reload
            # races with another lifecycle event.
            import logging
            logging.getLogger(__name__).warning(
                "LAN proxy auth applied but xray reload failed: %s", exc,
            )


# ── Internal helpers ──────────────────────────────────────────────────────────

async def _regenerate_and_write(session: AsyncSession, *, _self_heal_attempts: int = 0) -> None:
    """Re-generate xray config from current DB state and write it to
    disk, with pre-flight `xray run -test` validation.

    Self-healing (since v1.2.7): if validation fails because a routing
    rule references a geosite/geoip tag absent from the loaded `.dat`,
    we auto-disable the offending rules, append them to
    `Settings.auto_disabled_rules` (JSON list — surfaced by the
    frontend as a banner above the Routing table), and recursively
    retry the write with the smaller ruleset. Bounded to 5 attempts
    so a pathological `.dat` mismatch can't infinite-loop.
    """
    from app.core.config_gen import generate_config, write_config, collect_routing_set_context

    settings_map = await _load_settings_map(session)
    mode = settings_map.get("mode", "rules")
    active_id_str = settings_map.get("active_node_id", "")
    active_node = None
    if active_id_str:
        try:
            active_node = await session.get(Node, int(active_id_str))
        except ValueError:
            pass

    all_nodes = list((await session.exec(select(Node).where(Node.enabled == True))).all())
    rules = list((await session.exec(select(RoutingRule).where(RoutingRule.enabled == True))).all())
    dns_rules = list((await session.exec(select(DNSRule).where(DNSRule.enabled == True))).all())
    balancer_groups = list((await session.exec(select(BalancerGroup))).all())
    routing_sets, device_set_macs = await collect_routing_set_context(session)
    from app.models import NodeCircle
    from app.core.config_gen import resolve_active_circle
    circles = list((await session.exec(select(NodeCircle))).all())
    active_circle_id, active_circle_node_ids = resolve_active_circle(
        circles, active_node.id if active_node else None
    )
    config = generate_config(
        active_node, all_nodes, rules, mode, settings_map, dns_rules, balancer_groups,
        routing_sets=routing_sets, device_set_macs=device_set_macs,
        active_circle_id=active_circle_id, active_circle_node_ids=active_circle_node_ids,
    )

    # On retry passes we skip pre-flight to avoid recursive cost — the
    # outer attempt's pre-flight already proved which rules are bad,
    # and disabling them can't introduce new validation issues. Last
    # write of a healing chain re-runs with validate=True so the
    # success path clears `last_xray_validation_error`.
    heal_target = await write_config(config, validate=True)

    # Strict shape check — `heal_target` should be either None or a
    # 2-tuple of (str, str). Anything else (e.g. a stray mock or a
    # future schema change) is treated as None to avoid running the
    # self-heal path on garbage. Pre-1.2.7 callers + tests using
    # `AsyncMock(write_config)` without `return_value=None` would
    # otherwise see a MagicMock here and attempt recursion.
    if not (
        isinstance(heal_target, tuple)
        and len(heal_target) == 2
        and isinstance(heal_target[0], str)
        and isinstance(heal_target[1], str)
    ):
        return

    if _self_heal_attempts >= 5:
        # Give up: keep the current `last_xray_validation_error` set so
        # the admin still sees the underlying problem; don't loop.
        logger.error(
            "Self-heal exhausted (5 attempts) — leaving last_xray_validation_error in place"
        )
        return

    kind, tag = heal_target
    disabled_now = await _self_heal_disable_geo_rules(session, kind, tag)
    if not disabled_now:
        # No rules referenced the offending tag despite xray reporting
        # one — likely the rule was re-enabled or the parser disagrees
        # with xray. Stop trying to heal.
        logger.warning(
            "Self-heal: xray rejected %s:%s but no enabled rule references it; "
            "leaving config + error untouched", kind, tag,
        )
        return

    logger.info(
        "Self-heal disabled %d rule(s) referencing %s:%s — retrying config write (attempt %d)",
        len(disabled_now), kind, tag, _self_heal_attempts + 1,
    )
    await _regenerate_and_write(session, _self_heal_attempts=_self_heal_attempts + 1)


async def _self_heal_disable_geo_rules(
    session: AsyncSession, kind: str, tag: str
) -> List[int]:
    """Disable every enabled `RoutingRule` that references the given
    geosite/geoip tag, and append a record to the
    `Settings.auto_disabled_rules` JSON list. Returns the list of
    rule ids actually flipped.
    """
    from app.models import RoutingRule
    import json as _json
    from datetime import datetime as _dt, timezone as _tz

    rules = (await session.exec(
        select(RoutingRule).where(RoutingRule.enabled == True)
    )).all()

    affected: List[RoutingRule] = []
    needle_lc = tag.lower()
    for r in rules:
        rt = (r.rule_type or "").lower()
        mv = (r.match_value or "").lower()
        if rt == kind:
            parts = [p.strip() for p in mv.split(",") if p.strip()]
            if needle_lc in parts:
                affected.append(r)
        elif rt == "domain":
            # Inline `geosite:X` / `geoip:X` inside a domain-mode rule.
            inline = f"{kind}:{needle_lc}"
            parts = [p.strip() for p in mv.split(",") if p.strip()]
            if inline in parts:
                affected.append(r)

    if not affected:
        return []

    # Snapshot every attribute we'll need after commit() into plain
    # tuples — `session.commit()` expires SQLModel instance attrs by
    # default, and any subsequent attribute access triggers a lazy
    # reload that fails outside an awaitable context with
    # `MissingGreenlet` ("can't call await_only() here"). The
    # snapshot lets us read the values back without re-touching the
    # ORM after commit.
    snapshots = [
        (r.id, r.name, r.rule_type, r.match_value)
        for r in affected
    ]

    for r in affected:
        r.enabled = False
        session.add(r)

    # Append (rule_id, name, kind, tag, disabled_at) entries to the
    # settings key so the UI banner can show what happened. The list
    # acts as an inbox the admin clears explicitly via the banner's
    # "Re-enable" / "Delete" / "Dismiss" actions.
    row = (await session.exec(
        select(DBSettings).where(DBSettings.key == "auto_disabled_rules")
    )).first()
    try:
        existing = _json.loads(row.value) if row and row.value else []
        if not isinstance(existing, list):
            existing = []
    except Exception:
        existing = []

    now_iso = _dt.now(_tz.utc).isoformat(timespec="seconds")
    for rule_id, rule_name, rule_type, match_value in snapshots:
        existing.append({
            "rule_id": rule_id,
            "name": rule_name,
            "rule_type": rule_type,
            "match_value": match_value,
            "missing_kind": kind,
            "missing_tag": tag,
            "disabled_at": now_iso,
        })

    payload = _json.dumps(existing)
    if row:
        row.value = payload
        session.add(row)
    else:
        session.add(DBSettings(key="auto_disabled_rules", value=payload))

    await session.commit()
    # IDs returned from the pre-commit snapshot — `affected[i].id`
    # would re-fetch from the DB after the expire-on-commit.
    return [s[0] for s in snapshots]


async def _load_settings_map(session: AsyncSession) -> dict:
    rows = (await session.exec(select(DBSettings))).all()
    return {row.key: row.value for row in rows}


def _collect_bypass_macs(rules: List[RoutingRule]) -> List[str]:
    macs = []
    for rule in rules:
        if rule.rule_type == "mac" and rule.action == "direct":
            macs.extend(v.strip() for v in rule.match_value.split(","))
    return macs


def _collect_bypass_dsts(rules: List[RoutingRule]) -> List[str]:
    cidrs = []
    for rule in rules:
        if rule.rule_type == "dst_ip" and rule.action == "direct":
            cidrs.extend(v.strip() for v in rule.match_value.split(","))
    return cidrs


async def _collect_naive_bypass_dsts(session: AsyncSession) -> List[str]:
    """
    Resolve IPs of all enabled naive upstream servers → /32 CIDRs.
    Used to prevent the tproxy output-chain loop for the sidecar's socket.
    Domain names are resolved via ``socket.getaddrinfo`` (A records only).

    Resolution runs OFF the event loop thread (``asyncio.to_thread``)
    and with a 2-second per-host budget. The earlier sync version
    blocked the entire FastAPI event loop when /etc/resolv.conf was
    misconfigured — observed in the wild on 192.168.1.4 during 1.3.3
    burn-in: every API endpoint that touched ``_auto_reload_xray``
    (routing-rule CRUD, ``/system/restart``) stalled forever because
    the underlying ``getaddrinfo`` call wedged the loop while glibc
    retried against zero nameservers.

    DNS-broken or host-unreachable cases are absorbed silently
    (worst case: loop prevention doesn't apply until the host
    resolves again — non-fatal).
    """
    import asyncio
    import socket as _sock

    nodes = list((await session.exec(
        select(Node).where(Node.protocol == "naive", Node.enabled == True)  # noqa: E712
    )).all())
    out: List[str] = []

    def _resolve_one(host: str) -> List[str]:
        try:
            infos = _sock.getaddrinfo(host, None, _sock.AF_INET, _sock.SOCK_STREAM)
        except Exception:
            return []
        results: List[str] = []
        for fam, _, _, _, sa in infos:
            if fam == _sock.AF_INET and sa and sa[0]:
                results.append(f"{sa[0]}/32")
        return results

    for n in nodes:
        host = (n.address or "").strip()
        if not host:
            continue
        try:
            cidrs = await asyncio.wait_for(
                asyncio.to_thread(_resolve_one, host),
                timeout=2.0,
            )
        except asyncio.TimeoutError:
            # Don't block reload pipelines on a slow / broken DNS path.
            # Log once per host, not per-call to avoid spam.
            logger.warning(
                "naive bypass: DNS resolution of %r timed out — skipping. "
                "Check /etc/resolv.conf if this persists.",
                host,
            )
            continue
        out.extend(cidrs)

    # Dedup while preserving order
    seen = set()
    uniq = []
    for c in out:
        if c not in seen:
            seen.add(c)
            uniq.append(c)
    return uniq
